version: '3'

services:
    app:
        image: registry.digitalocean.com/lessgap/seo-sites:latest
        working_dir: /app
        volumes:
            - app-volume:/app
            - ./websites:/app/websites
            - ./.env:/app/.env
            - ./storage:/app/storage
    nginx:
        build: ./docker/nginx
        container_name: seo_sites_nginx
        volumes:
            - app-volume:/app
            - ./docker/nginx/conf.d/server.conf:/etc/nginx/conf.d/server.conf
            - ./storage/uploads:/app/public/uploads
        environment:
            NGINX_NO_CACHE: ${NGINX_NO_CACHE}
            NGINX_PAGESPEED: 1
            NGINX_PAGESPEED_IMG: 1
            NGINX_PAGESPEED_JS: 1
            NGINX_PAGESPEED_CSS: 1
        restart: on-failure
        depends_on:
            - app
            - websites
        ports:
            - ${APP_PORT}:9100
    redis:
        image: 'redis'
        restart: unless-stopped
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
volumes:
    app-volume:
        driver: local


