version: '3'

services:
    app:
        build: .
        working_dir: /var/www
        user: ${MY_UID}:${MY_GID}
        command: 'bash -c "composer install && php artisan serve --host=0.0.0.0 --port=80"'
        networks:
            - apisix
        volumes:
            - ./:/var/www
            - ./database.sqlite:/var/www/database.sqlite
            - ./public/index.php:/var/www/public/index.php
    nginx:
        build: ./docker/nginx
        user: ${MY_UID}:${MY_GID}
        container_name: po5
        depends_on:
            - app
        networks:
            - apisix
        volumes:
            - ./public:/var/www/public
            - ./docker/nginx/conf.d/server.conf:/etc/nginx/conf.d/server.conf
            - ./storage/uploads:/var/www/public/uploads
        environment:
            NGINX_NO_CACHE: ${NGINX_NO_CACHE}
            NGINX_PAGESPEED: 1
            NGINX_PAGESPEED_IMG: 1
            NGINX_PAGESPEED_JS: 1
            NGINX_PAGESPEED_CSS: 1
        ports:
            - ${APP_PORT}:9100
        restart: on-failure
networks:
    apisix:
        external: true
